# Generated by Django 5.0.4 on 2024-04-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee',
        ),
    ]
