# Generated by Django 5.0.4 on 2024-04-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
    ]
