# Generated by Django 5.0.4 on 2024-07-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_emp_id_ticket_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='employee',
            new_name='employee_db_id',
        ),
    ]
