# Generated by Django 5.0.3 on 2024-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
