# Generated by Django 5.0.3 on 2024-03-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Leave Type',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=20, null=True)),
                ('emp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.leavetype')),
            ],
            options={
                'db_table': 'LeaveRequests',
            },
        ),
    ]
