# Generated by Django 5.0.3 on 2024-03-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
