# Generated by Django 5.0.4 on 2024-07-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='emp_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='emp_id',
            new_name='employee',
        ),
    ]
