# Generated by Django 5.0.4 on 2024-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfile',
            name='file',
            field=models.FileField(upload_to='Policy_files/'),
        ),
    ]
