# Generated by Django 5.0.3 on 2024-04-01 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department_created_at_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
