# Generated by Django 5.0.4 on 2024-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_mail',
            field=models.EmailField(max_length=100),
        ),
    ]
