# Generated by Django 5.0.4 on 2024-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
