# Generated by Django 5.0.4 on 2024-07-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='employee',
            new_name='employee_data',
        ),
    ]
