# Generated by Django 5.0.4 on 2024-07-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_rename_employee_asset_employee_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='employee_data',
            new_name='employee_db_id',
        ),
    ]
