# Generated by Django 5.0.4 on 2024-07-04 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_rename_asset_asset_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='returned_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
